artifact_location: /Workspace/Repos/andreas.forsberg@capgemini.com/mvp_ml_delivery-main/src/machine_learning_dir/Databricks/0
creation_time: 1689237460545
experiment_id: '0'
last_update_time: 1689237460545
lifecycle_stage: active
name: Default
